### ISSUE TITLE
Bring Umbrella to parity with ErpReborn

### ISSUE THREAD

**Issue by PurityControl** [PurityControl/rbd_umbrella#1]
The following needs to be brought into the umbrella app either as a live view replacement or as is.
Functionality must only be improved on - their can be no regressions.

## Existing work
- [ ] Customer crud
- [ ] webshop / materials  mapping
- [ ] Product Classifications (was only skeleton in ERP Reborn)
- [ ] Material Requirement CSV download
- [ ] User Crud
- [ ] Misc -> Recall
- [ ] Misc -> Goods in R missing IMS
- [ ] Controlled Docs -> Capas
- [ ] Controlled Docs -> NCFs
- [ ] Access / Authorisaton / Login / Logout
- [ ] Back to ERP
- [ ] Better Menu

## WIP Work
- [ ] Supplier Approval
- [ ] Goods in versioning
